package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.GitHubAppConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubAppConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<GitHubAppConnection> {
            githubAppConnection {
                id = "PROJECT_EXT_3102"
                displayName = "tcbs-qwerqwerqwerqwersdfdv"
                appId = "1150953"
                clientId = "Iv23liTOZDqfWxnRGNT1"
                clientSecret = "credentialsJSON:0c9d1674-a618-467c-b1c3-e386a4a3b8a3"
                privateKey = "credentialsJSON:ffe87294-a15e-4a6e-aa18-68f146dc4d13"
                webhookSecret = "credentialsJSON:936bd040-6ca7-4cc4-b122-84910d3ffbf8"
                ownerUrl = "https://github.com/t120891923"
                useUniqueCallback = true
            }
        }
        feature1.apply {
        }
    }
}
